# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creating_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2017, 3, 20, 13, 54, 30, 529738, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
